name: tests
on:
  - push
  - pull_request

jobs:
  check-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add LLVM apt key
        run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm-toolchain-focal-18.asc

      - name: Add LLVM repo
        run: sudo add-apt-repository 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-18 main'

      - name: Install new clang-format
        run: sudo apt-get install clang-format-18

      - name: Check formatting
        run: python ${{ github.workspace }}/scripts/check_format.py --clang-format=clang-format-18

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
    env:
      build_dir: ${{ github.workspace }}/build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install libfmt-dev libpq-dev

      - name: Configure CMake
        run: cmake -B ${{ env.build_dir }} -S ${{ github.workspace }}

      - name: Build tests
        run: cmake --build ${{ env.build_dir }}
