name: tests
on:
  - push
  - pull_request

jobs:
  check-format:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check formatting
        run: python ${{ github.workspace }}/scripts/check_format.py

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
    env:
      build_dir: ${{ github.workspace }}/build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install libfmt-dev libpq-dev

      - name: Configure CMake
        run: cmake -B ${{ env.build_dir }} -S ${{ github.workspace }}

      - name: Build tests
        run: cmake --build ${{ env.build_dir }}
