name: tests
on:
  push:
    branches:
      - main
      - mac-ci
  pull_request:

jobs:
  check-format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check formatting
        run: python ${{ github.workspace }}/scripts/check_format.py --clang-format=clang-format-18

  check-tidy:
    runs-on: ubuntu-24.04
    env:
      build_dir: ${{ github.workspace }}/build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install libfmt-dev libpq-dev libsqlite3-dev

      - name: Configure CMake
        run: cmake -B ${{ env.build_dir }} -S ${{ github.workspace }} -DPFR_ORM_TEST:BOOL=ON

      - name: Run clang-tidy
        run: python ${{ github.workspace }}/scripts/tidy.py --clang-tidy=run-clang-tidy-18 --compile-commands=${{ env.build_dir }}

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        compiler:
          - g++
          - clang++
    env:
      build_dir: ${{ github.workspace }}/build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install libfmt-dev libpq-dev libsqlite3-dev

      - name: Configure CMake
        run: CXX=${{ env.compiler }} cmake -B ${{ env.build_dir }} -S ${{ github.workspace }} -DPFR_ORM_ASAN:BOOL=ON -DPFR_ORM_TEST:BOOL=ON

      - name: Build tests
        run: cmake --build ${{ env.build_dir }}

  test-gsl:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-14
    env:
      build_dir: ${{ github.workspace }}/build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: brew install fmt postgresql cpp-gsl

      - name: Configure CMake
        run: CXX=${{ env.compiler }} cmake -B ${{ env.build_dir }} -S ${{ github.workspace }} -DPFR_ORM_ASAN:BOOL=ON -DPFR_ORM_TEST:BOOL=ON -DPFR_ORM_USE_GSL_SPAN:BOOL=ON

      - name: Build tests
        run: cmake --build ${{ env.build_dir }}
