name: tests
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - windows-2022
    env:
      build_dir: ${{ github.workspace }}/build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: vcpkg install fmt libpq

      - name: Configure CMake
        run:  cmake -B ${{ env.build_dir }} -S ${{ github.workspace }}

      - name: Build tests
        run:  cmake --build ${{ env.build_dir }}
